apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.core.command}}
  name: {{.Values.edgex.app.core.command}}
spec:
  replicas: {{.Values.edgex.replicas.core.command}}
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.app.core.command}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.app.core.command}}
    spec:
      containers:
      - name: {{.Values.edgex.app.core.command}}
        image: {{.Values.edgex.image.core.command.repository}}:{{.Values.edgex.image.core.command.tag}}
        imagePullPolicy: {{.Values.edgex.image.core.command.pullPolicy}}
        ports:
        - containerPort: 48082
        env:
        - name: edgex_registry
          value: consul://{{.Values.edgex.app.core.consul}}:8500
        - name: EDGEX_SECURITY_SECRET_STORE
          value: "false"
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48082
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48082
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
      {{- if .Values.edgex.resources.core.command.enforceLimits }}
        resources:
          limits:
            memory: {{ .Values.edgex.resources.core.command.limits.memory }}
            cpu: {{ .Values.edgex.resources.core.command.limits.cpu }}
          requests:
            memory: {{ .Values.edgex.resources.core.command.requests.memory }}
            cpu: {{ .Values.edgex.resources.core.command.requests.cpu }}
      {{- end}}
      hostname: {{.Values.edgex.app.core.command}}
      restartPolicy: Always
status: {}
