apiVersion: v1
kind: Service
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.app.appservice.rules}}
  name: {{.Values.edgex.app.appservice.rules}}
spec:
  ports:
  - name: "48100"
    port: 48100
    targetPort: 48100
  selector:
    org.edgexfoundry.service: {{.Values.edgex.app.appservice.rules}}
status:
  loadBalancer: {}
