apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    org.edgexfoundry.service: {{.Values.edgex.scheduler.name}}
  name: {{.Values.edgex.scheduler.name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      org.edgexfoundry.service: {{.Values.edgex.scheduler.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        org.edgexfoundry.service: {{.Values.edgex.scheduler.name}}
    spec:
      containers:
      - name: {{.Values.edgex.scheduler.name}}
        image: edgexfoundry/docker-support-scheduler-go:1.1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 48085
        env:
        - name: edgex_registry
          value: consul://{{.Values.edgex.consul.name}}:8500
        - name: Clients_CoreData_Host
          value: {{.Values.edgex.data.name}}
        - name: Clients_Logging_Host
          value: {{.Values.edgex.logging.name}}
        - name: EDGEX_SECURITY_SECRET_STORE
          value: "false"
        - name: Logging_EnableRemote
          value: "true"
        readinessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48085
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/v1/ping
            port: 48085
          initialDelaySeconds: 15
          periodSeconds: 30
          successThreshold: 1
          failureThreshold: 3
        resources: {}
      initContainers:
      - name: wait-for-consul
        image: busybox:1.28
        command: ['sh', '-c', 'until wget edgex-core-consul:8500; do echo waiting for consul; sleep 2; done;']
      hostname: {{.Values.edgex.scheduler.name}}
      restartPolicy: Always
status: {}
